### ISSUE TITLE
Connection bug while stop listening

### ISSUE THREAD

**Issue by SlothSimon** [spacechase0/StardewValleyMP#18]
Hi, I encountered a bug while trying to migrate the mod to Mac OSX.

When the server starts host, the program will create a new thread to wait clients' connections.
After the client has connected to the server, **I clicked the "Start" button to stop listening**.
Then the server won't enter game and the terminal will throw out error information as follows:

> Stopping listener, beginning loading
> Exception while listening:
> Exception while listening for clients:
> interrupted

That really confused me because after stopping listener there shouldn't be exception of listening. But I finally figure it out.

Part of codes in Function **startHost() of Multiplayer.cs** is like this:

``` C#
try
{
    int port = Int32.Parse(portStr);
    listener = new TcpListener(IPAddress.IPv6Any, port);
    listener.Server.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false);
    listener.Start();

    client = null;
    server = new Server();

    while (true)
    {
        Log.Async("Waiting for connection...");
        Socket socket = listener.AcceptSocket();
        NetworkStream stream = new NetworkStream(socket);
        server.addClient(socket, stream);
    }

}
catch (Exception e)
{
    if (e is SocketException && ( ( ( SocketException ) e ).Message.IndexOf( "A blocking operation was interrupted" ) != -1 || ( ( SocketException ) e ).Message.IndexOf( "WSACancelBlockingCall" ) != -1 ) )
        return;

    Log.Async("Exception while listening: " + e);
    ChatMenu.chat.Add(new ChatEntry(null, "Exception while listening for clients: "));
    ChatMenu.chat.Add(new ChatEntry(null, e.Message));
    ChatMenu.chat.Add(new ChatEntry(null, "Check your log file for more details."));
    problemStarting = true;
}
finally
{
    if ( listener != null )
    {
        listener.Stop();
        listener = null;
    }
}
```

I noticed that the **while-cycle** will continue forever in this minor thread, which means the **codes in finally** will never be executed except catching errors. 

At the same time, some codes in Function **receiveLeftClick() in NewLoadMenu.cs** is like this:

``` C#
if (r.Contains(x, y))
{
    StardewModdingAPI.Log.Async("Stopping listener, beginning loading");
    Multiplayer.listener.Server.Close();
    readyToLoad = true;
}
```

`Multiplayer.listener.Server.Close();` this statement will close the listener outside the minor thread. Thus, the minor thread will catch errors then the server can't start game.

To solve the problem, I checked the last version of Multiplayer.cs and made some little modifications.

In while-cycle of **startHost() of Multiplayer.cs**:

``` C#
// outside the Function
public static bool stopListening = false;

// unrelated codes
... 
// while-cycle in startHost()
while (true)
{
    Log.Async("Waiting for connection...");
    Socket socket = listener.AcceptSocket();
    NetworkStream stream = new NetworkStream(socket);
    server.addClient(socket, stream);
    if (stopListening)
        break;
}
```

And in **receiveLeftClick() in NewLoadMenu.cs**:

``` C#
if (r.Contains(x, y))
{
    StardewModdingAPI.Log.Async("Stopping listener, beginning loading");
    // Multiplayer.listener.Server.Close();
    Multiplayer.stopListening = true;
    readyToLoad = true;
}
```

Then I can play multiplayer mode in Mac! (Although I don't know whether there are other run-time errors due to Mac OSX system)

I'm not sure if this bug happens **only on Mac** and I saw the related codes in 0.2.6 version remained unchanged. So I submit this issue to check whether the problem is only on Mac.

Thank you! : )

**Comment by spacechase0** [comment]
I believe it is a Mac issue. You can see at the beginning of the catch that I check for "WSACancelBlockingCall".

What happens is when I stop the listener, it throws the exception. However since it was intentional, I skip the error code.

So the exception while listening gives no message at all?

**Comment by SlothSimon** [comment]
Here is the error message:
```
[09:58:38.414 上午] [DEBUG] Menu changed from: None to TitleMenu
[09:59:40.427 上午] [] NOTE: Chat doesn't work on the connection menu.
[09:59:40.437 上午] Waiting for connection...
[09:59:53.384 上午] Got new client.
[09:59:53.401 上午] Waiting for connection...
[09:59:54.276 上午] Got farmer data for client 1
[09:59:54.741 上午] [] client has connected.
[10:00:04.470 上午] Stopping listener, beginning loading
[10:00:04.474 上午] Exception while listening: System.Net.Sockets.SocketException: interrupted
  at System.Net.Sockets.Socket.Accept () <0x160cdf9c0 + 0x000c4> in <filename unknown>:0 
  at System.Net.Sockets.TcpListener.AcceptSocket () <0x160cdf830 + 0x0002a> in <filename unknown>:0 
  at StardewValleyMP.Multiplayer.startHost () <0x160ccb740 + 0x00196> in <filename unknown>:0 
[10:00:04.474 上午] [] Exception while listening for clients: 
[10:00:04.474 上午] [] Check your log file for more details.
[10:00:04.474 上午] [] interrupted
```

**Comment by spacechase0** [comment]
Well. That's not a very helpful error message.

Do you know if there is some way to detect if you are on a Mac? I imagine I could check for "interrupted" like I do "WSACancelBlockingCall". I don't want to check for interrupted all the time though since I don't know if any other socket exceptions have that word.

**Comment by SlothSimon** [comment]
Sorry, I tested it by moving files to mods folder and running game. I tried debugging while running game but failed due to my poor knowledge about Xamarin. 
I'll update once I have any clue.

**Comment by spacechase0** [comment]
While it probably won't fix this issue, in the future a separate compilation won't be needed.
https://github.com/ClxS/SMAPI/issues/166

**Comment by spacechase0** [comment]
I'm assuming the platform issues are fixed for now. Let me know if that isn't the case.
