### ISSUE TITLE
Client relationship appears on Host's Social tab (and vica versa).

### ISSUE THREAD

**Issue by ItsSmiffy** [spacechase0/StardewValleyMP#26]
The Client's relationship is appearing on the Host's Social tab (and vica versa).

Screenshots are from the host's game.

Host is in a relationship with Abigail. Client is in a relationship with Sebastian. The Client's relationship appears in the Host's social tab. It is also happening the other way around (Host's relationship is appearing on the Client).

I am using v0.2.8. Didn't notice it using pre-v 0.2.8.

![social-pt1](https://cloud.githubusercontent.com/assets/18706783/19366052/7b5db7ea-918d-11e6-95f9-8ca503d9acd1.png)
![social-pt2](https://cloud.githubusercontent.com/assets/18706783/19366057/7e74eb10-918d-11e6-80b2-b9dc0303095d.png)

**Comment by spacechase0** [comment]
Yeah, that's been there a while. I kinda know of a fix but it will be tedious to write.
