### ISSUE TITLE
Chest synchronization error

### ISSUE THREAD

**Issue by avarisc** [spacechase0/StardewValleyMP#30]
It seems that chests are not synchronized correctly when there is more than just host and a single client.

Example scenario:
Client A places a chest and puts 1 stone in it.
Client B opens the chest, they will not see the stone.
The host comes to investigate, and sure enough the chest is empty.
The chest is now empty for Client A as well. The stone has been lost.

That scenario sucks when its a chest full of valuables, instead of 1 stone.

Alternative scenario:
Client A places a chest and puts 1 stone in it.
Host opens chest. It has one stone in it.
Client B opens the chest, and sure enough, it still has one stone in it.

So what's happening?
Client A is sending the update to the host when they place the stone and close the chest.
Client B is unaware of this update and still believes the chest to be empty.
If client B opens the chest at this point, it overwrites the host's copy of the chest with an empty one.
If the host opens it before client B, it sees the update from client A and sends it to all clients.

How to fix?
When the host receives a chest update, it needs to be immediately sent out to everyone, instead of when the host closes the chest.  If this is already the case, it isn't working correctly.

**Comment by spacechase0** [comment]
Ah, not sure how I missed this. I haven't tested more than 2 players in so long.

**Comment by avarisc** [comment]
I'm going to call this one fixed.  Technically there is still a window of a few milliseconds (for packet travel time) where the issue can occur - but excluding bad lag, it shouldn't happen under normal conditions.

**Comment by spacechase0** [comment]
Plus, the mod isn't intended to be 100% perfect, just good enough until official MP comes out.

The current system is pretty awful for a "real" multiplayer, since pretty much everyone is authoritative. (A hacked client could easily wreck your world without moving, although it couldn't make you save it.)
