### ISSUE TITLE
Opening Barn/Coop doors blows up building

### ISSUE THREAD

**Issue by silentdragonz** [spacechase0/StardewValleyMP#39]
If you open the animal doors on the barn or coop the building blows up. I commented out this if statement [5f03dfa](https://github.com/spacechase0/StardewValleyMP/commit/5f03dfa4d7b1154709d45e896356865f27646407#diff-949f030d35f4f7f18f0c6400028b3cf1R363) to stop it from happening for now.

**Comment by spacechase0** [comment]
Should be fixed in 8c81f97.
