### ISSUE TITLE
Dark Talisman

### ISSUE THREAD

**Issue by tiansh** [spacechase0/StardewValleyMP#47]
Dark Talisman has only shared one, which means second person cannot get it.

**Comment by tiansh** [comment]
#17

**Comment by spacechase0** [comment]
What do you mean by 'has only shared one'? Can both people not do the quest?

**Comment by tiansh** [comment]
if first people pick up the dark talisman, then the second one cannot got it.

only the first people can do the quest, but second one cannot finish it any more
