### ISSUE TITLE
OSX connecting to win host, System.DllNotFoundException 

### ISSUE THREAD

**Issue by dooglz** [spacechase0/StardewValleyMP#69]
Can't join a windows host from my MacBook, an exception is thrown and nothing happens
Exception sending: System.DllNotFoundException: libMonoPosixHelper.dylib. Logfile attached
[SMAPI-latest.txt](https://github.com/spacechase0/StardewValleyMP/files/1142053/SMAPI-latest.txt)

**Comment by spacechase0** [comment]
You and the host need to set "Compress" to false in the config file.
